const mockup = [
  {
    stock: 5,
    type: "food",
    name: "Pad Thai",
    score: 5,
    price: 60,
    img: "/src/assets/img/ผัดไท.png",
  },
  {
    stock: 10,
    type: "food",
    name: "Fried rice with pork",
    score: 3,
    price: 50,
    img: "/src/img/ข้าวผัดหมู.jpg",
  },
  {
    stock: 6,
    type: "food",
    name: "Fried rice with crab",
    score: 4,
    price: 75,
    img: "/src/img/ข้าวผัดปู.jpg",
  },
  {
    stock: 9,
    type: "food",
    name: "Fried rice with squid",
    score: 4,
    price: 75,
    img: "/src/img/กระเพรา.png",
  },
  {
    stock: 7,
    type: "food",
    name: "Tom Yum Kung",
    score: 5,
    price: 90,
    img: "/src/img/ต้มยำกุ้ง.jpg",
  },
  {
    stock: 0,
    type: "food",
    name: "Chicken and galangal soup",
    score: 4,
    price: 60,
    img: "/src/img/ต้มข่าไก่.jpg",
  },
  {
    stock: 7,
    type: "food",
    name: "Chicken Green Curry",
    score: 3,
    price: 50,
    img: "/src/img/แกงเขียวหวานไก่.jpg",
  },
  {
    stock: 2,
    type: "food",
    name: "Roast chicken",
    score: 4,
    price: 40,
    img: "/src/img/ไก่ย่าง.jpg",
  },
  {
    stock: 0,
    type: "food",
    name: "Papaya salad",
    score: 5,
    price: 50,
    img: "/src/img/ส้มตำ.jpg",
  },
  {
    stock: 2,
    type: "food",
    name: "Charcoal pork",
    score: 4,
    price: 65,
    img: "/src/img/คอหมูย่าง.jpeg",
  },
  {
    stock: 2,
    type: "food",
    name: "Charcoal pork",
    score: 4,
    price: 65,
    img: "/src/img/คอหมูย่าง.jpeg",
  },
  {
    stock: 10,
    type: "food",
    name: "Rice",
    score: 5,
    price: 10,
    img: "/src/img/ข้าว.jpg",
  },
  {
    stock: 10,
    type: "food",
    name: "Sticky Rice",
    score: 4,
    price: 10,
    img: "/src/img/ข้าวเหนียว.jpg",
  },
  {
    stock: 10,
    type: "drink",
    name: "Water",
    score: 3,
    price: 10,
    img: "/src/img/น้ำ.jpg",
  },
  {
    stock: 5,
    type: "drink",
    name: "Lemon Tea",
    score: 4,
    price: 40,
    img: "/src/img/ชามะนาว.png",
  },
  {
    stock: 5,
    type: "drink",
    name: "Milk Tea",
    score: 4,
    price: 40,
    img: "/src/img/ชานม.jpg",
  },
  {
    stock: 12,
    type: "drink",
    name: "Coke",
    score: 5,
    price: 25,
    img: "/src/img/Coke.jpg",
  },
  {
    stock: 10,
    type: "drink",
    name: "Pepsi",
    score: 5,
    price: 25,
    img: "/src/img/เป๊ปซี่.jpg",
  },
  {
    stock: 0,
    type: "drink",
    name: "Coffee Latte",
    score: 4,
    price: 60,
    img: "/src/img/ลาเต้.jpg",
  },
  {
    stock: 4,
    type: "dessert",
    name: "Thai tea ice cream",
    score: 5,
    price: 60,
    img: "/src/img/Thai tea ice cream.jpg",
  },
  {
    stock: 8,
    type: "dessert",
    name: "Mango sticky rice",
    score: 4,
    price: 100,
    img: "/src/img/มะม่วง.jpg",
  },
  {
    stock: 0,
    type: "dessert",
    name: "Pudding",
    score: 4,
    price: 85,
    img: "/src/img/caramel-castard-taco-bell.jpg",
  },
  {
    stock: 9,
    type: "dessert",
    name: "Crepe",
    score: 4,
    price: 70,
    img: "/src/img/Crepe.jpg",
  },
  {
    stock: 0,
    type: "dessert",
    name: "Layer Cake",
    score: 4,
    price: 120,
    img: "/src/img/Layer Cake.jpeg",
  },
  {
    stock: 5,
    type: "dessert",
    name: "Fresh Fruit",
    score: 5,
    price: 80,
    img: "/src/img/Fresh Fruit.jpg",
  },
];

export default mockup;
