const mockup = [
  {
    id: 1,
    stock: 0,
    type: "food",
    name: "Pad Thai",
    score: 5,
    price: 60,
    img: "/src/img/ผัดไท.png",
  },
  {
    id: 2,
    stock: 6,
    type: "food",
    name: "Spaghetti with sausage",
    score: 3,
    price: 75,
    img: "/src/img/สปาเก็ตตี้.png",
  },
  {
    id: 3,
    stock: 3,
    type: "food",
    name: "Fried rice with squid",
    score: 4,
    price: 80,
    img: "/src/img/กระเพรา.png",
  },
  {
    id: 4,
    stock: 5,
    type: "drink",
    name: "Lemon Tea",
    score: 4,
    price: 40,
    img: "/src/img/ชามะนาว.png",
  },
  {
    id: 5,
    stock: 0,
    type: "drink",
    name: "Cocktail",
    score: 5,
    price: 80,
    img: "/src/img/cocktail_10.jpg",
  },
  {
    id: 6,
    stock: 20,
    type: "drink",
    name: "Coffee Latte",
    score: 4,
    price: 60,
    img: "/src/img/ลาเต้.jpg",
  },
  {
    id: 7,
    stock: 4,
    type: "dessert",
    name: "Thai tea ice cream",
    score: 5,
    price: 60,
    img: "/src/img/เค้ก.jpg",
  },
  {
    id: 8,
    stock: 8,
    type: "dessert",
    name: "Mango sticky rice",
    score: 4,
    price: 100,
    img: "/src/img/มะม่วง.jpg",
  },
  {
    id: 9,
    stock: 0,
    type: "dessert",
    name: "Cream caramel",
    score: 4,
    price: 50,
    img: "/src/img/caramel-castard-taco-bell.jpg",
  },
];

export default mockup;
