const mockup = [
  {
    stock: 0,
    type: "food",
    name: "Pad Thai",
    score: 5,
    price: 5.99,
    img: "/src/img/ผัดไท.png",
  },
  {
    stock: 6,
    type: "food",
    name: "Spaghetti with sausage",
    score: 3,
    price: 11.99,
    img: "/src/img/สปาเก็ตตี้.png",
  },
  {
    stock: 3,
    type: "food",
    name: "Fried rice with squid",
    score: 4,
    price: 11.99,
    img: "/src/img/กระเพรา.png",
  },
  {
    stock: 5,
    type: "drink",
    name: "Lemon Tea",
    score: 4,
    price: 1.99,
    img: "/src/img/ชามะนาว.png",
  },
  {
    stock: 6,
    type: "drink",
    name: "Cocktail",
    score: 5,
    price: 4.99,
    img: "/src/img/cocktail_10.jpg",
  },
  {
    stock: 20,
    type: "drink",
    name: "Coffee Latte",
    score: 4,
    price: 2.99,
    img: "/src/img/ลาเต้.jpg",
  },
  {
    stock: 4,
    type: "dessert",
    name: "Thai tea ice cream",
    score: 5,
    price: 2.25,
    img: "/src/img/เค้ก.jpg",
  },
  {
    stock: 8,
    type: "dessert",
    name: "Mango sticky rice",
    score: 4,
    price: 3.99,
    img: "/src/img/มะม่วง.jpg",
  },
  {
    stock: 7,
    type: "dessert",
    name: "Cream caramel",
    score: 4,
    price: 1.99,
    img: "/src/img/caramel-castard-taco-bell.jpg",
  },
];

export default mockup;
